[package]
name = "chariwtbeach"
version = "0.1.0"
authors = ["Michael Richardson <mcr@sandelman.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor = "0.10"


